FROM python:3.10

ADD crawler /opt/crawler
COPY setup.ini /opt/crawler
COPY loggingConfig.json /opt/crawler
RUN mkdir /opt/crawler/logData
WORKDIR /opt/crawler

RUN python3 -m pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "crawler:app", "--host", "0.0.0.0", "--port", "7000"]